version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Preparing build...
  build:
    commands:
      - echo Building the app...
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
